services:
  postgres:
    image: postgres:18-alpine
    container_name: bitka-postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${AUTH_DB_NAME} # Default DB
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bitka-net

  auth-service:
    container_name: bitka-auth
    build:
      context: .
      dockerfile: services/Dockerfile.auth
      args:
        SERVICE: auth
    ports:
      - "${AUTH_PORT}:${AUTH_PORT}"
    env_file:
      - .env
    environment:
      SERVICE: auth
      APP_ENV: production
      DB_HOST: postgres
      # Map specific name to generic name expected by Go App
      DB_NAME: ${AUTH_DB_NAME} 
      KAFKA_BROKER: kafka:9092
    depends_on:
      - postgres
    networks:
      - bitka-net

  account-service:
    container_name: bitka-account
    build:
      context: .
      dockerfile: services/Dockerfile.account
      args:
        SERVICE: account
    ports:
      - "${ACCOUNT_PORT}:${ACCOUNT_PORT}"
    env_file:
      - .env
    environment:
      SERVICE: account
      APP_ENV: production
      DB_HOST: postgres
      # Map specific name to generic name
      DB_NAME: ${ACCOUNT_DB_NAME}
      HTTP_PORT: ${ACCOUNT_PORT}
      # Docker internal networking
      AUTH_JWKS_URL: http://auth-service:${AUTH_PORT}/.well-known/jwks.json
      KAFKA_BROKER: kafka:9092
    depends_on:
      - postgres
      - auth-service
    networks:
      - bitka-net
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - bitka-net

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_BROKER_ID: 1
    depends_on:
      - zookeeper
    networks:
      - bitka-net


volumes:
  postgres_data:

networks:
  bitka-net:
    driver: bridge
