services:
  # --- Traefik ---
  traefik:
    image: traefik:v3.6.4
    container_name: bitka-gateway
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - bitka-net
    labels:
      - "traefik.enable=true"

      # --- Define CORS Middleware (Global) ---
      # Name: 'cors-headers'

      # 1. Allow Origins: In Dev use '*', in Prod use specific domain
      - "traefik.http.middlewares.cors-headers.headers.accesscontrolalloworiginlist=*"

      # 2. Allow Methods: GET, POST, PUT, DELETE, OPTIONS
      - "traefik.http.middlewares.cors-headers.headers.accesscontrolallowmethods=GET,POST,PUT,DELETE,OPTIONS"

      # 3. Allow Headers: What headers can the frontend send? (Auth, Content-Type, Trace-ID)
      - "traefik.http.middlewares.cors-headers.headers.accesscontrolallowheaders=Content-Type,Authorization"

      # 4. Max Age: How long browser caches the CORS check (seconds)
      - "traefik.http.middlewares.cors-headers.headers.accesscontrolmaxage=100"

      # 5. Add Vary Header: Good for caching
      - "traefik.http.middlewares.cors-headers.headers.addvaryheader=true"

  # --- Postgres ---
  postgres:
    image: postgres:18-alpine
    container_name: bitka-postgres
    restart: always
    env_file:
      - ../../.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: maintenance_db
      POSTGRES_MULTIPLE_DATABASES: ${POSTGRES_DATABASES}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    networks:
      - bitka-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d maintenance_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # --- Kafka ---
  kafka:
    image: apache/kafka:4.1.1
    container_name: kafka
    ports:
      - "9092:9092" # Exposed for Host (go run)
    environment:
      # KRaft Settings
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      # Listener Configuration
      # 1. CONTROLLER: Internal voting (Port 9093)
      # 2. OUTSIDE:    Host access (Port 9092) - For local dev
      # 3. INSIDE:     Docker access (Port 29092) - For containers
      KAFKA_LISTENERS: CONTROLLER://:9093,OUTSIDE://:9092,INSIDE://:29092
      KAFKA_ADVERTISED_LISTENERS: OUTSIDE://localhost:9092,INSIDE://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,OUTSIDE:PLAINTEXT,INSIDE:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - bitka-net

  # --- Kafka UI ---
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8081:8080" # Access at http://localhost:8081
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      DYNAMIC_CONFIG_ENABLED: "true"
    networks:
      - bitka-net

volumes:
  postgres_data:
  kafka_data:

networks:
  bitka-net:
    driver: bridge
